FORMAT: 1A
HOST: http://www.google.com

# Demagog
REST API for mobile apps.

# Group Articles
## Articles Collection [/api/v1/articles{?limit}{?olderthan}]

+ Parameters
    + limit (optional, number, `10`) ... maximum number of returned items
    + olderthan (optional, long, `1393927929`) ... requesting older articles published before this date (Unix epoch time in seconds)

### List articles [GET]
+ Response 200 (application/json)

        [
           {
              "id":585,
              "type":"discussion",
              "title":"Stav slovenskej ekonomiky",
              "image":"http://www.demagog.sk/data/diskusia/s/139267094974.jpg",
              "perex":"Demagog.SK overil len jednu z nedeľných diskusných relácií a postupne svoje sily presúvame na overovanie prezidentských kandidátov.",
              "publishedAt":1393927929,
              "politicians":[
                 {
                    "id":45545,
                    "name":"Jozef Kollár",
                    "image":"http://www.demagog.sk/data/politik/t/130545286325.jpg",
                    "statistics":{
                       "true":12,
                       "untrue":58,
                       "misleading":22,
                       "unverifiable":5
                    },
                    "party":{
                       "id":4,
                       "name":"SaS",
                       "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
                       "membersCount":52,
                       "statistics":{
                          "true":12,
                          "untrue":58,
                          "misleading":22,
                          "unverifiable":5
                       }
                    }
                 }
              ]
           }
        ]
        
## Article [/api/v1/articles/{id}]
A single Article object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of article

### Retrieve a Article [GET]
+ Response 200 (application/json)
    
        {
           "id":585,
           "title":"Stav slovenskej ekonomiky",
           "image":"http://www.demagog.sk/data/diskusia/s/139267094974.jpg",
           "text":"Demagog.SK overil len jednu z nedeľných diskusných relácií a postupne svoje sily presúvame na overovanie prezidentských kandidátov. Kažimír a Kollár diskutovali o nových číslach z Inštitútu finančnej politiky, predovšetkým o medzere vo výbere DPH. Kollár tieto čísla nemal presne naštudované, správne ho...",
           "publishedAt":1393927929,
           "politicians":[
              {
                 "id":45545,
                 "name":"Jozef Kollár",
                 "image":"http://www.demagog.sk/data/politik/t/130545286325.jpg",
                 "party":{
                    "id":4,
                    "name":"SaS",
                    "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
                    "membersCount":52,
                    "statistics":{
                       "true":12,
                       "untrue":58,
                       "misleading":22,
                       "unverifiable":5
                    }
                 },
                 "statistics":{
                    "true":12,
                    "untrue":58,
                    "misleading":22,
                    "unverifiable":5
                 },
                 "statements":[
                    {
                       "id":4554,
                       "important":false,
                       "text":"Keď sa bavíme o nezosobášených pároch, existuje 21 zákonov, kde nemôžu požívať rovnaké výhody ako manželia.",
                       "evaluation":"untrue"
                    }
                 ]
              }
           ],
           "source":{
              "name":"O 5 minút 12",
              "date":1393927929,
              "host":"Martin Strižinec",
              "url":"www.blabla.com/bla"
           }
        }




# Group Statements
## Statements Collection [/api/v1/statements{?party}{?politician}{?important}{?limit}{?olderthan}]

+ Parameters
    + party (optional, long, `1`) ... filter only statements of specified party
    + politician (optional, long, `1`) ... filter only statements of specified politician
    + limit (optional, long, `10`) ... maximum number of returned items
    + important (optional, bool, `true`) ... filter only important statements
    + olderthan (optional, string, `1393927929`) ... requesting older statements published before this date

### List statements [GET]
+ Response 200 (application/json)

        [
           {
              "id":4554,
              "important":false,
              "text":"Keď sa bavíme o nezosobášených pároch, existuje 21 zákonov, kde nemôžu požívať rovnaké výhody ako manželia.",
              "evaluation":"untrue",
              "publishedAt":1393927929,
              "politician":{
                 "id":45545,
                 "name":"Jozef Kollár",
                 "image":"http://www.demagog.sk/data/politik/t/130545286325.jpg",
                 "party":{
                       "id":4,
                       "name":"SaS",
                       "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
                       "membersCount":52,
                       "statistics":{
                          "true":12,
                          "untrue":58,
                          "misleading":22,
                          "unverifiable":5
                       }
                    }
              },
              "source":{
                 "name":"O 5 minút 12",
                 "date":1393927929,
                 "host":"Martin Strižinec",
                 "url":"www.blabla.com/bla"
              }
           }
        ]
        
## Statement [/api/v1/statements/{id}]
A single Statement object with all its details

+ Parameters
    + id (required, number, `1`) ... id of statement

### Retrieve a statement [GET]
+ Response 200 (application/json)

        [
           {
              "id":4554,
              "important":false,
              "text":"Keď sa bavíme o nezosobášených pároch, existuje 21 zákonov, kde nemôžu požívať rovnaké výhody ako manželia.",
              "evaluation":"untrue",
              "publishedAt":1393927929,
              "politician":{
                 "id":45545,
                 "name":"Jozef Kollár",
                 "image":"http://www.demagog.sk/data/politik/t/130545286325.jpg",
                 "party":{
                       "id":4,
                       "name":"SaS",
                       "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
                       "membersCount":52,
                       "statistics":{
                          "true":12,
                          "untrue":58,
                          "misleading":22,
                          "unverifiable":5
                       }
                    }
              },
              "source":{
                 "name":"O 5 minút 12",
                 "date":"1393927929",
                 "host":"Martin Strižinec",
                 "url":"www.blabla.com/bla"
              },
              "explanation":"Na základe údajov z Eurostatu nie je viditeľná výrazná zmena v pôrodnosti, či rozvodovosti v krajinách, ktoré prijali inštitút úradného manželstva, registrovaného partnerstva alebo podobný právny inštitút. Z tohto dôvodu hodnotíme výrok za pravdivý..."
           }
        ]




# Group Parties
## Parties Collection [/api/v1/parties]
### List all parties [GET]
+ Response 200 (application/json)

        [
           {
              "id":4,
              "name":"SaS",
              "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
              "membersCount":52,
              "statistics":{
                 "true":12,
                 "untrue":58,
                 "misleading":22,
                 "unverifiable":5
              }
           }
        ]





# Group Politicians
## Politicians Collection [/api/v1/politicians{?party}]

+ Parameters
    + party (optional, id, `1`) ... filter only politicians of specified party

### List politicians [GET]
+ Response 200 (application/json)

        [
           {
              "id":4,
              "name":"Martin Poliačik",
              "image":"http://www.demagog.sk/data/politik/t/130545286325.jpg",
              "statistics":{
                 "true":12,
                 "untrue":58,
                 "misleading":22,
                 "unverifiable":5
              },
              "party":{
                 "id":4,
                 "name":"SaS",
                 "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
                 "membersCount":52,
                 "statistics":{
                    "true":12,
                    "untrue":58,
                    "misleading":22,
                    "unverifiable":5
                 }
              }
           }
        ]

## Politician [/api/v1/politicians/{id}]
A single politician object with all its details

+ Parameters
    + id (required, number, `1`) ... id

### Retrieve a politician [GET]
+ Response 200 (application/json)

        {
           "id":4,
           "name":"Martin Poliačik",
           "image":"http://www.demagog.sk/data/politik/t/130545286325.jpg",
           "statistics":{
              "true":12,
              "untrue":58,
              "misleading":22,
              "unverifiable":5
           },
           "party":{
              "id":4,
              "name":"SaS",
              "image":"http://www.demagog.sk/data/politicke_strany/t/1290591022.jpg",
              "membersCount":52,
              "statistics":{
                 "true":12,
                 "untrue":58,
                 "misleading":22,
                 "unverifiable":5
              }
           }
        }

